"""Regenerate experiments/_reference/E01..E15.md from the code (maintenance).

    python scripts/make_references.py                   # offline: stub models, stub decider, fixtures
    python scripts/make_references.py --live-decisions  # also E04, E05, E13 with the local Laya decider

Each file records the date, the run mode, and the models, so a reference result can be compared with a
new run. Work happens in temporary runs folders; local state is not touched.
"""

from __future__ import annotations

import datetime as dt
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
OUT = ROOT / "experiments" / "_reference"
OFFLINE = {"app.force_offline": True, "apis.live": False}
TODAY = dt.date.today().isoformat()


def header(eid: str, title: str, mode: str) -> str:
    return (f"# {eid} reference results: {title}\n\nGenerated by `scripts/make_references.py` on {TODAY}; "
            f"{mode}. Numbers come from the code as it stands; a new run replaces them.\n\n")


def use_runs(path: Path) -> None:
    os.environ["COPILOT_RUNS_DIR"] = str(path)


def settings(profile: str, **overrides):
    from campus_copilot import config

    return config.get_settings(profile, {**OFFLINE, **overrides})


def ingest(profile: str, runs: Path, **overrides) -> dict:
    from campus_copilot.ingest import pipeline

    use_runs(runs)
    return pipeline.run_ingest(settings(profile, **{"ingest.sources": ["data/sources"], **overrides}),
                               store="all", echo=lambda _: None)


def eval_summary(profile: str, subset: str | None, factory=None, **overrides):
    from campus_copilot.evaluation.runner import run_eval

    return run_eval(settings(profile, **overrides) if not factory else live_settings(profile, **overrides),
                    subset=subset, echo=None, copilot_factory=factory)


def live_settings(profile: str, **overrides):
    from campus_copilot import config

    return config.get_settings(profile, {"apis.live": False, **overrides})


def stub_chat_factory(s):
    from campus_copilot.graph.build import Copilot
    from campus_copilot.llm.client import LLM
    from campus_copilot.llm.stub import StubClient

    return Copilot(s, llm=LLM([StubClient()], s), small_llm=LLM([StubClient()], s))


def checks_row(name: str, run) -> str:
    s = run.summary
    c = s["checks"]
    return (f"| {name} | {s['passed']}/{s['scored']} | {c['route']} | {c['tools']} | {c['citation']} | {c['facts']} | "
            f"{c['abstain']} | {s['latency_p50_ms']} | {s['tokens_per_case']} |")


CHECKS_HEAD = ("| Setting | Passed | Route | Tools | Citation | Key facts | Abstain | p50 ms | Tokens per case |\n"
               "|---|---|---|---|---|---|---|---:|---:|")


def main() -> int:
    live = "--live-decisions" in sys.argv
    OUT.mkdir(parents=True, exist_ok=True)
    base = Path(tempfile.mkdtemp(prefix="refs-"))
    pack = base / "pack"
    ingest("offline", pack)
    mode = "offline mode (stub models, keyword stub decider, recorded fixtures)"

    def fresh(name: str) -> Path:
        path = base / name
        shutil.copytree(pack, path)
        use_runs(path)
        return path

    # E01 -------------------------------------------------------------------------
    fresh("e01")
    rows = [checks_row(p, eval_summary(p, "handbook,follow_up,unanswerable"))
            for p in ("baseline", "e01_zero_shot", "e01_free_text", "e01_hot")]
    (OUT / "E01.md").write_text(header("E01", "prompt anatomy and structured output", mode) + CHECKS_HEAD + "\n" +
                                "\n".join(rows) + "\n\nThe stub model ignores prompt style and temperature, so offline rows "
                                "match; the differences appear with a live chat model.\n", encoding="utf-8")

    # E02 -------------------------------------------------------------------------
    lines = ["| Setting | Chunks | Tokens per chunk en / km (median) | Chunks over window | Probe hit@3 |", "|---|---:|---|---:|---:|"]
    for profile in ("baseline", "e02_chunk_small", "e02_chunk_large", "e02_chars", "e02_window256", "e02_no_pdf"):
        state = ingest(profile, base / f"e02-{profile}")
        chunk = state["stages"]["chunk"]["stats"]
        spread = chunk["token_spread"]
        med = " / ".join(str(spread.get(lang, {}).get("median", "-")) for lang in ("en", "km"))
        lines.append(f"| {profile} | {chunk['chunks']} | {med} | {len(chunk['over_window'])} | "
                     f"{state['stages']['verify']['stats']['hit_rate']} |")
    sample = ingest("e02_window256", base / "e02-window-sample")["stages"]["chunk"]["stats"]["over_window"][:1]
    dropped = (sample[0]["dropped_text"][:200].replace("\n", " ") + " ...") if sample else "-"
    (OUT / "E02.md").write_text(header("E02", "chunking, token budgets, and silent failures", mode) + "\n".join(lines) +
                                f"\n\nText a 256-token embedder would silently drop from one chunk:\n\n> {dropped}\n\n"
                                "The `input_type` swap needs NIM embeddings: the offline hashing encoder is symmetric, "
                                "so `e02_swap` changes nothing offline.\n", encoding="utf-8")

    # E03 -------------------------------------------------------------------------
    from campus_copilot.rag.compare import compare

    fresh("e03")
    tables = [compare(q, settings("baseline"), k=3).markdown() for q in
              ("What is the yearly tuition fee for Cyber Security?", "What is the cafeteria menu on Friday?",
               "តើអាចខ្ចីសៀវភៅបានប៉ុន្មានក្បាល?")]
    (OUT / "E03.md").write_text(header("E03", "retrieval pipelines, vector stores, and abstention", mode) +
                                "\n\n".join(tables) + "\n", encoding="utf-8")

    # E04 / E05 / E13 decisions -----------------------------------------------------
    from campus_copilot.db import connection, queries
    from campus_copilot.decisions import questions as qcat
    from campus_copilot.decisions.base import get_decider

    fresh("e04")
    conn = connection.read_connection()
    catalogue = qcat.turn_catalogue(queries.course_codes(conn))
    spec = qcat.wire(catalogue)
    messages = [t["message"] for t in map(json.loads, (ROOT / "data" / "demo_turns.jsonl").read_text(
        encoding="utf-8").splitlines())][:12]
    deciders = [("keyword stub", get_decider(settings("baseline"), kind="keyword"))]
    if live:
        deciders.append(("Laya (live)", get_decider(live_settings("e05_laya"), kind="laya")))
    rows = ["| Decider | Message | route (confidence) | currency_direction | amount_stated | follow_up | missing_info |",
            "|---|---|---|---|---|---|---|"]
    for name, decider in deciders:
        for message in messages:
            d = decider.decide(qcat.turn_state(message, [], "A0001", ["FECO303", "FECS329"]), spec)
            if not d.ok:
                rows.append(f"| {name} | {message} | request failed ({d.status}) | | | | |")
                continue
            route, conf, _ = d.choice("route")
            rows.append(f"| {name} | {message} | {route} ({conf:.2f}) | {d.choice('currency_direction')[0]} | "
                        f"{d.noul('amount_stated'):.2f} | {d.noul('follow_up'):.2f} | {d.noul('missing_info'):.2f} |")
    (OUT / "E04.md").write_text(header("E04", "decision-model basics",
                                       mode + (" plus the Laya decider" if live else "")) + "\n".join(rows) + "\n",
                                encoding="utf-8")
    fresh("e05")
    rows = [checks_row("e05_keyword (routing subset)", eval_summary("e05_keyword", "routing"))]
    rows.append(checks_row("e05_keyword (full set)", eval_summary("e05_keyword", None)))
    if live:
        rows.append(checks_row("e05_laya live (routing subset)", eval_summary("e05_laya", "routing", stub_chat_factory)))
        rows.append(checks_row("e05_laya live (full set)", eval_summary("e05_laya", None, stub_chat_factory)))
    (OUT / "E05.md").write_text(header("E05", "three ways to route", mode + (" plus Laya rows (stub chat model)"
                                                                            if live else "")) + CHECKS_HEAD + "\n" +
                                "\n".join(rows) + "\n\nThe LLM router needs a live chat model; offline it falls back to "
                                "the stub and matches the keyword row.\n", encoding="utf-8")

    # E06 / E08 / E09 / E11 / E15 evaluation comparisons ---------------------------
    def comparison(eid: str, title: str, profiles: list[str], subset: str | None, note: str = "") -> None:
        fresh(eid.lower())
        rows = [checks_row(p, eval_summary(p, subset)) for p in profiles]
        (OUT / f"{eid}.md").write_text(header(eid, title, mode) + CHECKS_HEAD + "\n" + "\n".join(rows) + "\n" + note,
                                       encoding="utf-8")

    comparison("E06", "tool calling three ways", ["e06_native", "e06_json", "e06_laya_dispatch"],
               "multi_step,rooms,library", "\nOffline, the stub model drives all three modes with the same plan; "
               "live models differ in tool choice and argument errors.\n")
    comparison("E08", "agent loop, and when not to use one", ["e08_calls_1", "baseline", "e08_calls_8",
                                                               "e08_agent_on", "e08_agent_off"], "multi_step,timetable,library")
    comparison("E09", "memory, follow-ups, and state", ["baseline", "e09_condense_off", "e09_condense_always",
                                                         "e09_window_0", "e09_window_2"], "follow_up")
    comparison("E11", "evaluation harness and three judges", ["baseline", "e11_lexical"], None)
    comparison("E15", "the decision ladder", ["e15_long_context", "baseline"], "handbook",
               "\nLong context sends every handbook chunk in each prompt: compare tokens per case.\n")

    # E07 -------------------------------------------------------------------------
    from campus_copilot.graph.build import Copilot

    fresh("e07")
    rows = ["| Question | Templates: tools | Text-to-SQL: SQL | Result |", "|---|---|---|---|"]
    templ = Copilot(settings("baseline"))
    sql = Copilot(settings("e07_text_to_sql", **{"guards.enabled": False}))
    for q in ["When are the FECO303 assignments due?", "Is ISBN 9780262046305 on the shelf?",
              "Show the library loans of A0007.", "Show the loans'; DROP TABLE loans;--"]:
        a, b = templ.ask(q), sql.ask(q)
        call = b.tool_calls[0] if b.tool_calls else {}
        outcome = "ok" if call.get("ok") else (call.get("data") or {}).get("stopped_by") or call.get("error", b.kind)
        rows.append(f"| {q} | {', '.join(c['tool'] for c in a.tool_calls) or a.kind} | "
                    f"`{(call.get('data') or {}).get('sql', '-')}` | {outcome} |")
    templ.close(), sql.close()
    (OUT / "E07.md").write_text(header("E07", "templates vs text-to-SQL", mode) + "\n".join(rows) + "\n", encoding="utf-8")

    # E10 -------------------------------------------------------------------------
    from campus_copilot.graph.demo import run_demo

    fresh("e10")
    boards = {}
    for label, transport in (("in-process", "inprocess"), ("MCP", "mcp")):
        copilot = Copilot(settings("baseline", **{"tools.transport": transport, "app.today": "2026-10-06"}))
        boards[label] = (run_demo(copilot).passed, copilot.rt.transport.name)
        copilot.close()
    (OUT / "E10.md").write_text(header("E10", "MCP servers", mode) + "| Transport | Demo turns passing | Transport used |\n"
                                "|---|---|---|\n" + "\n".join(f"| {k} | {len(v[0])}/14 {v[0]} | {v[1]} |"
                                                               for k, v in boards.items()) + "\n", encoding="utf-8")

    # E12 -------------------------------------------------------------------------
    from campus_copilot.observability.report import build_report, load_spans, render

    parts = []
    for profile in ("baseline", "e12_routing"):
        fresh(f"e12-{profile}")
        copilot = Copilot(settings(profile, **{"app.today": "2026-10-06"}))
        run_demo(copilot)
        copilot.close()
        parts.append(f"## {profile}\n\n" + render(build_report(load_spans(), settings(profile).profile.get("prices"))))
    (OUT / "E12.md").write_text(header("E12", "traces, latency, and cost", mode) + "\n\n".join(parts) + "\n",
                                encoding="utf-8")

    # E13 -------------------------------------------------------------------------
    adv = base / "e13"
    shutil.copytree(pack, adv)
    use_runs(adv)
    from campus_copilot.ingest import pipeline

    pipeline.run_ingest(settings("e13_attacks", **{"ingest.sources": ["data/sources"]}), echo=lambda _: None)
    rows = ["| Case | OWASP | Expected control | Controls on | Controls off |", "|---|---|---|---|---|"]
    on = {r["id"]: r for r in eval_summary("baseline", "adversarial").rows}
    off = {r["id"]: r for r in eval_summary("e13_controls_off", "adversarial").rows}
    cases = {c["id"]: c for c in map(json.loads, (ROOT / "eval" / "cases.jsonl").read_text(encoding="utf-8").splitlines())}
    for cid in on:
        rows.append(f"| {cid} | {cases[cid].get('owasp')} | {cases[cid].get('expected_control')} | "
                    f"{on[cid]['kind']}: {on[cid]['answer'][:70]} | {off[cid]['kind']}: {off[cid]['answer'][:70]} |")
    extra = ""
    if live:
        live_on = eval_summary("baseline", "adversarial", stub_chat_factory)
        extra = f"\n\nWith the Laya decider: {live_on.summary['passed']}/{live_on.summary['scored']} adversarial cases caught.\n"
    (OUT / "E13.md").write_text(header("E13", "prompt injection and tool-layer safety", mode) + "\n".join(rows) + extra +
                                "\n", encoding="utf-8")

    # E14 -------------------------------------------------------------------------
    from campus_copilot.evaluation.vision import render as vision_render
    from campus_copilot.evaluation.vision import run_vision_eval
    from campus_copilot.graph.nodes import Runtime

    fresh("e14")
    (OUT / "E14.md").write_text(header("E14", "reading a notice with a vision model", mode) +
                                vision_render(run_vision_eval(Runtime(settings("baseline")))) +
                                "\n\nLive check on 23 Sep 2026 (docs/verify-at-build.md): Gemma 4 through Google AI Studio "
                                "read the clean and the Khmer-script posters correctly.\n", encoding="utf-8")
    shutil.rmtree(base, ignore_errors=True)
    for path in sorted(OUT.glob("E*.md")):
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
